import { User, Category, Email } from '@prisma/client';
import { encrypt } from '../../src/utils/encryption';
import { v4 as uuidv4 } from 'uuid';

export interface TestUser {
  id: string;
  email: string;
  googleId: string;
  accessToken: string;
  refreshToken: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface TestCategory {
  id: string;
  userId: string;
  name: string;
  description: string;
  color: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface TestEmail {
  id: string;
  userId: string;
  categoryId?: string | null;
  gmailMessageId: string;
  accountEmail: string;
  subject: string;
  from: string;
  to: string;
  date: Date;
  body: string;
  bodyHtml?: string | null;
  aiSummary: string;
  isArchived: boolean;
  isDeleted: boolean;
  unsubscribeLink?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

// Factory functions to create mock data
export const createMockUser = (overrides: Partial<User> = {}): User => {
  const now = new Date();
  return {
    id: uuidv4(),
    email: `test-${uuidv4().substring(0, 8)}@example.com`,
    googleId: `google-${uuidv4()}`,
    accessToken: encrypt('test-access-token'),
    refreshToken: encrypt('test-refresh-token'),
    createdAt: now,
    updatedAt: now,
    ...overrides,
  };
};

export const createMockCategory = (userId: string, overrides: Partial<Category> = {}): Category => {
  const now = new Date();
  return {
    id: uuidv4(),
    userId,
    name: `Test Category ${uuidv4().substring(0, 8)}`,
    description: 'A test category for testing purposes',
    color: '#3B82F6',
    createdAt: now,
    updatedAt: now,
    ...overrides,
  };
};

export const createMockEmail = (userId: string, overrides: Partial<Email> = {}): Email => {
  const now = new Date();
  return {
    id: uuidv4(),
    userId,
    categoryId: null,
    gmailMessageId: `gmail-${uuidv4()}`,
    accountEmail: 'test@example.com',
    subject: 'Test Email Subject',
    from: 'sender@example.com',
    to: 'recipient@example.com',
    date: now,
    body: 'This is a test email body',
    bodyHtml: '<p>This is a test email body</p>',
    aiSummary: 'This is a test email summary generated by AI',
    isArchived: false,
    isDeleted: false,
    unsubscribeLink: 'https://example.com/unsubscribe',
    createdAt: now,
    updatedAt: now,
    ...overrides,
  };
};

// Mock request object for authentication
export function createMockAuthRequest(user: User | null = null) {
  return {
    user,
    isAuthenticated: () => !!user,
    login: jest.fn((u, cb) => cb(null)),
    logout: jest.fn((cb) => cb(null)),
    session: {},
    params: {},
    query: {},
    body: {},
  };
}

// Mock response object
export function createMockResponse() {
  const res: any = {
    status: jest.fn().mockReturnThis(),
    json: jest.fn().mockReturnThis(),
    send: jest.fn().mockReturnThis(),
    redirect: jest.fn().mockReturnThis(),
  };
  return res;
}

// Helper to wait for async operations
export const waitFor = (ms: number) =>
  new Promise((resolve) => setTimeout(resolve, ms));

// Mock email message data
export const createMockEmailMessage = (overrides = {}) => ({
  id: 'mock-message-id',
  threadId: 'mock-thread-id',
  subject: 'Mock Email Subject',
  from: 'sender@example.com',
  to: 'recipient@example.com',
  date: new Date().toISOString(),
  body: 'This is a mock email body',
  bodyHtml: '<p>This is a mock email body</p>',
  snippet: 'This is a snippet',
  headers: [
    { name: 'Subject', value: 'Mock Email Subject' },
    { name: 'From', value: 'sender@example.com' },
    { name: 'To', value: 'recipient@example.com' },
  ],
  ...overrides,
});

// Mock Gmail API responses
export const mockGmailListResponse = {
  data: {
    messages: [
      { id: 'msg-1', threadId: 'thread-1' },
      { id: 'msg-2', threadId: 'thread-2' },
    ],
    resultSizeEstimate: 2,
  },
};

export const mockGmailMessageResponse = {
  data: {
    id: 'msg-1',
    threadId: 'thread-1',
    snippet: 'This is an email snippet',
    payload: {
      headers: [
        { name: 'Subject', value: 'Test Subject' },
        { name: 'From', value: 'sender@example.com' },
        { name: 'To', value: 'recipient@example.com' },
        { name: 'Date', value: new Date().toISOString() },
      ],
      body: {
        data: Buffer.from('Test email body').toString('base64'),
      },
    },
  },
};
